import "@/styles/globals.css";
import { StateProvider } from "@/utils/stateProvider/StateProvider";

export const metadata = {
  title: "Pharmaceutical Module | BlockMed Pro Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full max-w-[2140px] mx-auto">
        <StateProvider>
          {children}
        </StateProvider>
      </body>
    </html>
  );
}
